language: java

after_failure:
- cat build/reports/tests/test/index.html

matrix:
  include:
    - jdk: openjdk8
      install: true
    - jdk: openjdk11
      install: true
    - jdk: openjdk12
      install: true

script: ./gradlew clean test --info