language: java

after_failure:
- cat build/reports/tests/test/index.html

matrix:
  include:
    - jdk: openjdk8
      install: true
    - jdk: openjdk9
      install: true
    - jdk: openjdk10
      install: true
    - jdk: openjdk11
      install: true
